ARG SRC=wagoodman
FROM ${SRC}/dive AS dive

FROM docker
ARG SRC=wagoodman

LABEL dive.source.registry="Docker Hub"
LABEL dive.source.repo="${SRC}/dive"
LABEL dive.source.link="https://hub.docker.com/repository/docker/${SRC}/dive"

COPY --from=dive /usr/local/bin/dive /usr/local/bin/